### ISSUE TITLE
CRM 2016

### ISSUE THREAD

**Issue by kiquenet** [josephmcmac/XRM-Developer-Tool#1]
Working for CRM 2016 ? How I put Credentials for connect to CRM ?

**Comment by josephmcmac** [comment]
Yes the code is all 2016 compatible and I have used it with CRM 2016

The Discovery Service Address and Organisation Unique ID are still accessible in the 2016 Web UI at Settings -> Customizations -> Developer Resources

If it is a CRM Online instance use "Live ID / Office 365" Authentication Type and the email address as the login. If it is on premise then use either Federation for IFD or otherwise Active Directory or Window Integrated Authentication Type

You may need install or turn on Windows Identity Foundation 3.5 if it is not already and you receive an error containing "Could not load file or assembly'Microsoft.IdentityModel, Version=3.5...

If you are receiving a specific error then maybe let me know the details and I could take a look
