### ISSUE TITLE
Field match conflict  when migrating multiple portal webpages with same name

### ISSUE THREAD

**Issue by ktast** [josephmcmac/XRM-Developer-Tool#257]
Hi Josheph and congrats for your efforts keeping the app up-to-date and for your openness sharing it.

Today I was using it to migrate portal records (Web Pages) and it seems like when you have a Web Page with the same Name (different parent Page for example) it migrate over on the first one and not all of them

**Comment by ktast** [comment]
can we use the GUID instead  ?

**Comment by josephmcmac** [comment]
Hi @ktast 

This issue will be related to the D365 platform automatically creating the child language specific webpage when a new parent webpage record is created. Due to this the primary key of that webpage in the target instance will not be consistent with the primary key of the record in the source data

When doing portal configurations my solution to this problem was just using a different name for all webpages, sometimes just suffixing it with something appropriate

I could potentially add code to handle this scenario by rewriting the primary key of the child webpage in the source data at the point the source parent page is created

I'll keep the issue open but unfortunately due to other work commitments I won't be able to work on a fix for it yet

**Comment by ktast** [comment]
Thanks for getting back to me so soon @josephmcmac ! I've figured the same thing changing the name. Worked just fine 😉
