### ISSUE TITLE
Support for ILMerge

### ISSUE THREAD

**Issue by Shadowing01** [josephmcmac/XRM-Developer-Tool#262]
A lot of my plugins or workflows use ILMerge and create a new DLL post build using ILMerge.MSBuild.Task.
By default, this creates a folder called 'ILMerge' inside the output folder, containing the merged DLL.
At the moment, I can only use the developer tool on plugins without dependencies, which works great!
Can you create support for ILMerge?

**Comment by josephmcmac** [comment]
I have implemented an enhancement for this for the next release

- A new field in the Package Settings -> Plugin Projects grid named "Uses  ILMerge-MSBuild-Task" allows defining a project as using  ILMerge-MSBuild-Task. If checked then when deploying/updating the project assembly to D365 it will be loaded from the subpath ILMerge in the  project build output folder
- Note for the extension to work all assemblies (including SDK assemblies) must be set to Copy Local for the project. This is for loading the plugin types through reflection and means you cannot use the default ILMerge.MSBuild.Task option of merging all Copy Local output
- Due to the above you will need to use an ILMerge config file to limit the ILMerged assemblies as documented here https://github.com/emerbrito/ILMerge-MSBuild-Task/wiki#creating-a-static-list-of-assemblies-to-merge
