### ISSUE TITLE
wiki pls

### ISSUE THREAD

**Issue by phuocle** [josephmcmac/XRM-Developer-Tool#40]
your repo always up to date. need you creat wiki and put some documents that we can understand more.

**Comment by josephmcmac** [comment]
Hi there

I had initially looked to add documentation in the github wiki but found it
a bit difficult to use. I ended up documenting some of the features in this
blog https://josephmcmac.wordpress.com/

Specifically the blog has these categories for the app and visual studio
extension these may help
https://josephmcmac.wordpress.com/category/josephm-dynamics-365-dev-app/
https://josephmcmac.wordpress.com/category/josephm-xrm-vsix/

If there is something specific you want detailed let me know. I will look
to respond with some details and/or write an article on it. Otherwise I am
not entirely sure which specific areas of the code, or features would be
beneficial to write about

Regards
Joseph

**Comment by josephmcmac** [comment]
Closing this as need more details about what specific documentation would be beneficial
